# 注释掉或删除 theme 行
# theme: minima

# 换成远程主题（以 midnight为例）
remote_theme: "pages-themes/midnight"

# 必须添加这个插件
plugins:
  - jekyll-remote-theme
  - jekyll-feed  # 推荐加上

# 其他配置保持不变
title: cd1319的博客
description: 用Netlify CMS管理的博客
future: true
